# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: <%= ENV["DEV_TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["DEV_TWITTER_API_SECRET"] %>

development:
  secret_key_base: a82d229a3297d3f2ac83dd793f51fff3513deb3e1760808dc15f3dc0b2e55750c3a35cea9ee62dbfe784af6e876cdc54942b6a6323a8e4f7dffe4115a6c4d5bd
  <<: *default_twitter

test:
  secret_key_base: 2fcd1a16f79d820ae18d4ebaffdea3cbb81a0c3e28448721d08997b4804a10f3337c7664ad1228c499fd113be234767aaeb15087b6e441ff1cbc5727876df670
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["PRO_TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["PRO_TWITTER_API_SECRET"] %>